# Generated by Django 4.2 on 2025-11-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicegroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='devicegroup',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceData',
        ),
        migrations.DeleteModel(
            name='DeviceGroup',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
