# Generated by Django 4.2 on 2025-11-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_data_points_userprofile_devicegroup_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='data_points',
        ),
    ]
